name: "Running command and date"

on:
    push: #event
        - master
        - main

jobs:
    run-command-and-current-date: #job name
        runs-on: ubuntu-latest #env is light and fast

        steps:
            - name: "Run Hello World"
              run: echo "Hello World"

            - name: "Print Current Date"
              run: date

